### ISSUE TITLE
Rethinkdb with python driver installed

### ISSUE THREAD

**Issue by cirelli94** [rethinkdb/rethinkdb-dockerfiles#48]
It would be great to have an image with python and the [python driver](https://rethinkdb.com/docs/install-drivers/python/) already installed via pip.
I needed to use the rethinkdb command line utility that needs the python driver to dump, restore, etc.
Nowadays you have to sh in the container and install python-pip and the driver.
If this could be useful to someone other, I can make a pull request.

**Comment by TB-VHS** [comment]
1

**Comment by furibund** [comment]
👍

**Comment by gabor-boros** [comment]
@cirelli94 and @furibund, I think this would be a good idea! Since python2 is deprecated and the extended-extended end of life is in April, I guess it is ok for you to install the python3 version of the driver, am I right?

Do you have any concerns about installing the python 3 version?

**Comment by cirelli94** [comment]
Yes, I't ok to me.
I'll do it today or tomorrow, and I'll make a pull request :+1:

**Comment by cirelli94** [comment]
Mm if I install only the python 3 version I can't use dump and restore, probably because it fail to find the driver.
This it happens not only when I build an image with a dockerfile but even when I did it manually!

So I did:
```
$ apt install python3-pip
$ pip3 install rethinkdb==2.4
$ rethinkdb dump
# rethinkdb dump
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-dump", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/_dump.py", line 143, in main
    options = parse_options(argv or sys.argv[2:], prog=prog)
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/_dump.py", line 94, in parse_options
    options, args = parser.parse_args(argv)
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/utils_common.py", line 365, in parse_args
    'ssl': options.ssl
  File "/usr/local/lib/python3.6/dist-packages/rethinkdb/utils_common.py", line 50, in __init__
    if connect_options <= 0:
TypeError: '<=' not supported between instances of 'dict' and 'int' 

```

**Comment by gabor-boros** [comment]
Oh, nice. I’ll fix this tomorrow as soon as I can! By the way, it is time to drop python 2 finally
